[world]
name = "OnChain Sage"
description = "AI-driven decentralized trading assistant that combines real-time social sentiment analysis with on-chain market data to identify high-potential crypto tickers"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/degenspot/onchainsage"
seed = "onchainsage_mainnet"

[world.socials]
x = "https://x.com/onchainsage"
discord = "https://discord.gg/onchainsage"
github = "https://github.com/degenspot/onchainsage"
telegram = "https://t.me/+Tg-UnlqyEcAxODBk"

[namespace]
default = "onchainsage"

[env]
rpc_url = "https://starknet-mainnet.infura.io/v3/"
# Mainnet account (should be set via environment variables)
# account_address = ""
# private_key = ""

[writers]
"onchainsage" = ["onchainsage-actions", "onchainsage-token", "onchainsage-analytics"]
