[world]
name = "OnChain Sage"
description = "AI-driven decentralized trading assistant that combines real-time social sentiment analysis with on-chain market data to identify high-potential crypto tickers"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/degenspot/onchainsage"
seed = "onchainsage_dev"

[world.socials]
x = "https://x.com/onchainsage"
discord = "https://discord.gg/onchainsage"
github = "https://github.com/degenspot/onchainsage"
telegram = "https://t.me/+Tg-UnlqyEcAxODBk"

[namespace]
default = "onchainsage"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"onchainsage" = ["onchainsage-actions", "onchainsage-token", "onchainsage-analytics"]
