[world]
name = "OnChain Sage Testnet"
description = "OnChain Sage AI trading assistant on StarkNet Sepolia testnet"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/degenspot/onchainsage"
seed = "onchainsage_testnet"

[world.socials]
x = "https://x.com/onchainsage"
discord = "https://discord.gg/onchainsage"
github = "https://github.com/degenspot/onchainsage"
telegram = "https://t.me/+Tg-UnlqyEcAxODBk"

[namespace]
default = "onchainsage"

[env]
# StarkNet Sepolia Testnet
rpc_url = "https://starknet-sepolia.infura.io/v3/"
# These should be set via environment variables
# account_address = ""
# private_key = ""

[writers]
"onchainsage" = ["onchainsage-actions"]

# Testnet-specific settings
[testnet]
enable_debug = true
gas_limit = 1000000
max_retries = 3
confirmation_blocks = 1 